# This file was generated by Nuitka and describes the types of the
# created shared library.

# At this time it lists only the imports made and can be used by the
# tools that bundle libraries, including Nuitka itself. For instance
# standalone mode usage of the created library will need it.

# In the future, this will also contain type information for values
# in the module, so IDEs will use this. Therefore please include it
# when you make software releases of the extension module that it
# describes.

import threading
import OCC.Core.BRepBuilderAPI
import GUI.SelectWidget
import OCC.Core.gp
import sketcher.sketcher_circel
import sketcher.sketcher_line
import sketcher.sketcher_rectangle
import sketcher.sketcher_trim
import OCC.Core.GeomAPI
import OCC.Core
import OCC.Core.BRep
import OCC.Core.Geom
import OCC.Core.Prs3d
import OCC.Core.Quantity
import OCC.Core.TopoDS
import OCC.Core.GC
import OCC.Core.AIS
import math
import time
import OCC.Core.GCE2d
import OCC.Core.Graphic3d
import OCC.Core.TopExp
import PyQt5.QtGui
import numba
import OCC.Core.TopAbs
import OCC.Core.Aspect
import GUI
import OCC.Core.BRepTools
import OCC.Extend.TopologyUtils

# This is not Python source even if it looks so. Make it clear for
# now. This was decided by PEP 484 designers.
__name__ = ...

