# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Process_message_word.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QHBoxLayout,QVBoxLayout
from GUI.SketcherButton import SketcherButton

class SketcherWidget(QtWidgets.QMainWindow):
	def __init__(self, parent=None,mode=None):
		super(SketcherWidget, self).__init__(parent)
		self.parent=parent
		self.setupUi(parent)
		x = parent.Displayshape_core.canva.geometry().x() + parent.Displayshape_core.canva.geometry().width() / 2
		y = parent.Displayshape_core.canva.geometry().y() + parent.Displayshape_core.canva.geometry().height() / 2
		self.setGeometry(x, y, 80*3, 5*3)
		self.setWindowTitle('绘制矩形')
		#self.pushbutton_ok.clicked.connect(self.ok)
		#self.pushbutton_cancel.clicked.connect(self.cancel)
		
		
	
	def setupUi(self,parent):
		self.widget = QtWidgets.QWidget(self)
		#self.setMovable(False)
		#self.addWidget(self.widget)
		# self.setStyleSheet("background-color: rgb(14, 162, 185);")
		self.setCentralWidget(self.widget)
		HBOX = QVBoxLayout()
		HBOX_comboBOX=QVBoxLayout()
		HBOX_button = QHBoxLayout()
		self.widget.setLayout(HBOX)
		HBOX.addLayout(HBOX_comboBOX)
		HBOX.addLayout(HBOX_button)
		
		#self.comboBox = QtWidgets.QComboBox(self.widget)
		#self.comboBox.setGeometry(QtCore.QRect(80, 100, 221, 500))
		#self.comboBox.setObjectName("comboBox")
		#self.comboBox.addItem("XY平面")
		#self.comboBox.addItem("XZ平面")
		#self.comboBox.addItem("YZ平面")
		#HBOX_comboBOX.addWidget(self.comboBox,0, QtCore.Qt.AlignTop)

		#self.folder_pushButton = SketcherButton(self.widget, "folder_pushButton", "folder", [20, 20], "打开",
												 #parent.OCAF.Open_part)
		#HBOX_button.addWidget(self.folder_pushButton, 0)

		self.pushbutton_ok=QtWidgets.QPushButton()
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("icons/{}.png".format("矩形1")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.pushbutton_ok.setIcon(icon)
		self.pushbutton_ok.setIconSize(QtCore.QSize(35, 35))
		HBOX_button.addWidget(self.pushbutton_ok)

		self.pushbutton_ok = QtWidgets.QPushButton()
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("icons/{}.png".format("矩形2")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.pushbutton_ok.setIcon(icon)
		self.pushbutton_ok.setIconSize(QtCore.QSize(30, 30))
		HBOX_button.addWidget(self.pushbutton_ok)

		self.pushbutton_ok = QtWidgets.QPushButton()
		#self.pushbutton_ok.setFlat(True)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("icons/{}.png".format("矩形3")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.pushbutton_ok.setIcon(icon)
		self.pushbutton_ok.setIconSize(QtCore.QSize(30, 30))
		HBOX_button.addWidget(self.pushbutton_ok)




		
		#self.pushbutton_ok=QtWidgets.QPushButton("确定")
		#self.pushbutton_cancel = QtWidgets.QPushButton("取消")
		#HBOX_button.addWidget(self.pushbutton_ok)
		#HBOX_button.addWidget(self.pushbutton_cancel)
		#self.statusBar().showMessage("请选择草绘平面")
	def ok(self):
		self.parent.Sketcher.uptoplane()
		self.close()
		
	def cancel(self):
		self.close()
		
	def Show(self):
		self.show()
