# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Process_message_word.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class ProcessWidget(QtWidgets.QMainWindow):
	def __init__(self,parent=None):
		super(ProcessWidget, self).__init__(parent)
		self.setupUi()
		x=parent.geometry().x()+parent.geometry().width()/2
		y=parent.geometry().y()+parent.geometry().height()/2
		self.setGeometry(x,y,350,40)
		self.setWindowTitle('零件载入中.......')
		self.button.clicked.connect(self.Close)
		
	
	def setupUi(self):
		self.button=QtWidgets.QPushButton(self)
		self.button.setText("零件载入请稍等(点击终止载入)")
		self.setCentralWidget(self.button)
	
	def Show(self):
		self.show()
		print("show ")
	
	def Close(self):
		self.close()